apiVersion: confi.gurator.com/v1
kind: MultiTenancy
metadata:
  name: food-processor
spec:
  # We want one instace for each Food in our system (required)
  tenancyKind: food
  # Name the env variable for where to put the name of the food (optional)
  tenantNameVariable: FOOD_TYPE
  # Name the volume for where to put the food details (optional)
  tenantResourceVolume: which-food
  # Note: if the tenantResourceVolume is specified, the pod will be restarted for any change in the tenant's data.
  # However, if only tenantNameVariable is specified, the pod will not respond to changes in tenant data

  # The paused field can be set to true to pause handling of this MultiTenancy
  # paused: false

  eventHooks:
    - events:
        - deleted
      logConfig:
        regex: Apple
      slack:
        webhookURL: blah

  # Standard selector and template definition, much like for Deployments or StatefulSets:
  selector:
    matchLabels:
      app: food-processor
  template:
    metadata:
      labels:
        app: food-processor
    spec:
      containers:
      - name: food-processor
        image: busybox
        command:
          - 'sh'
          - '-c'
          - 'while true; do
              date;
              echo FOOD_TYPE: $FOOD_TYPE;
              for file in /etc/which-food/*; do
                echo $file;
                cat $file;
                echo;
              done;
              sleep 5;
            done'
        # Add a volume so we can know which Food this pod belongs to
        volumeMounts:
          - name: which-food
            mountPath: /etc/which-food
