apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "multitenancy.fullname" . }}
  labels:
{{ include "multitenancy.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - multitenancy
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - confi.gurator.com
  resources:
  - multitenancies
  - tenants
  - multitenancies/status
  - tenants/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
